name: Build Workflow
on: push
jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 11
          target-folder: javadoc 
          
      - name: View test results
        run: |
          cd ./Group21HW/src/com/group21/csc510/csv/lua
          javac *.java
          cd ..
          cd ..
          cd ..
          cd ..
          cd ..
          java -Xmx100m com.group21.csc510.csv.lua.Lua -e ALL
